<?php

namespace Ephect\Plugins\Setup;

use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useProps;

define('SERVER_ERROR', 'Something went wrong, please check the server setup');

function Install($props)
{

    useEffect(function ($props, /* bool */ $hasResponse, /* string */ $response, /* string */ $action) {
        $action = $props->action;
        $setup = new SetupService;

        if ($action === 'rewrite') {

            $ok = $setup->findFramework();
            $rewritebase = $setup->fixRewritBase();
            $response = json_encode(
                [
                    'result' => ($rewritebase !== null) ? $rewritebase : SERVER_ERROR,
                    'error' => ($rewritebase === null)
                ]
            );
        }

        if ($action === 'js') {
            $ok = $setup->installPhinkJS();
            $response = json_encode(
                [
                    'result' => ($ok) ? 'Javascript framework installation successful' : SERVER_ERROR,
                    'error' => !$ok
                ]
            );
        }

        if ($action === 'index') {

            $ok = $setup->makeBootstrap();
            $ok = $ok && $setup->makeIndex();
            $response = json_encode(
                [
                    'result' => ($ok) ? 'Index created' : SERVER_ERROR,
                    'error' => !$ok
                ]
            );
        }

        $hasResponse = ($response !== '');
    });

    return (<<<HTML
    <if (%hasResponse) {
        <ResponseHeader 
            directive[]="Content-Type: application/json"
            directive[]="Content-Encoding: utf-8"
        />
        {{ response }}
    }>
    HTML);
}
