<template id="CodeWriter">
    <div class="code-snippet">
        <div class="to-be-copied">
            <pre id="to-copy"><code class="language-php"></code></pre>
        </div>
        <div class="to-be-written">
            <pre id="to-write"><code class="language-php"></code></pre>
        </div>
    </div>
</template>
<script>
    import CodeWriter from "./CodeWriter.class.mjs"

    /**
     * Rename the component
     */
    class CodeWriterComponent extends HTMLElement {

        constructor() {
            super();

            this.source
            this.useHighlightJs

            this.attachShadow({
                mode: 'open'
            });
            this.shadowRoot.innerHTML = document.getElementById('CodeWriter').innerHTML

            const slots = this.shadowRoot.querySelectorAll('slot')
            if (slots.length) {
                slots[0].addEventListener('slotchange', event => {
                    console.dir(slots[0].assignedNodes())
                })
            }

        }

        static get observeAttributes() {
            /**
             * Attributes passed inline to the component
             */
            return ['source', 'use-highlight-js']
        }

        get source() {
            return this.getAttribute('source') ?? null
        }

        get useHighlightJs() {
            return this.getAttribute('use-highlight-js') ?? null
        }

        async connectedCallback() {
            /**
             * The magic starts here
             */
            const cw = new CodeWriter(this)
            cw.writeLikeAHuman('to-copy', 'to-write')
            const useHighlightJS = this.useHighlightJS

        }
    }

    customElements.define('code-writer', CodeWriterComponent);
</script>
<style>
    @import "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css"
</style>
<style>
    @import "https://highlightjs.org/static/demo/styles/base16/monokai.css"
</style>
<style>
    #to-copy {
        display: block;
        position: relative;
        float: left;
        width: 33vw;
    }

    #to-write {
        width: 33vw;
    }

    .to-be-copied {
        display: block;
        position: relative;
        float: left;
    }

    .to-be-written {
        display: flex;
        position: absolute;
        width: 33vw;
    }

    .code-snippet {
        display: flex;
        font-size: medium;
    }

    div,
    p,
    span,
    textarea {
        -tab-size: 4;
        -o-tab-size: 4;
        -moz-tab-size: 4;
    }
</style>