<?php

namespace Ephect\Plugins\WebComponent;

use function Ephect\Hooks\useEffect;

function WebComponent($children)
{

    useEffect(function($children, /* string */ $tag, /* string */ $args, $service) {

        $service = new WebComponentService($children);
        $manifest = $service->readManifest();
        $tag = $manifest->getTag();
        $args = $service->getAttributes();

    });

    return (<<< HTML
        <{{ tag }} {{ args }} />
        {? 
            if(!{service}->isPending()) {
                {service}->markAsPending(); 
                {@html} = { children };
                {service}->storeHTML({@html});
            }
        ?}
    HTML);
}
