<?php

namespace Fun;

use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useState;

function Com($props)
{
    useEffect(function () use ($props, /* string */ &$b, /* string */ &$c, /* string */ &$d, /* string */ &$m) {

        $b = 'It is a';
        $c = 'functional component';
        $d = $props->from;
        [$state, $setState] = useState();

        $m = $state->m->n;

        $setState(['p' => ['n' => 'q']]);
    });

    return (<<< HTML
    <h1>{{ props->message }}</h1>
    <sub>from {{ d }}</sub>
    <h2>{{ b }}</h2>
    <h3>{{ c }}</h3>
    <h3>{{ m }}</h3>
    <Dummy />
    HTML);
}
