<?php

namespace Ephect\Plugins\Router;

use Ephect\Framework\Registry\RouteRegistry;
use function Ephect\Hooks\useEffect;


function Router($children): string
{
    useEffect(function (/* bool */ $hasRouted, /* object */ $service, /* string */ $path, /* string */ $html) {

        $service = new RouterService;

        if (RouteRegistry::hasMoved()) {

            [$path, $query, $error, $code, $middlewares] = $service->doRouting();
            $service->renderRoute($code === 200, $path, $query, $error, $code, $middlewares, $html);

            $hasRouted = true;
        }
    });

    return (<<< HTML
        <%
            if(%hasRouted) { 
                { html }
                return;
            }
        %>
        {{ children }}
        <%            
            %service->moveCache();
            Builder::purgeCopies();

            %service->findRoute(%html);
            if(%html !== '') { 
                { html }
            } 

        %>
    HTML);
}
