<html data-color-mode="light" data-light-theme="light" data-dark-theme="dark" data-a11y-animated-images="system">

<head>
    <meta charset="UTF-8">

    <title>
        Ephect in action !
    </title>

    <meta property="og:image:alt"
        content="Make PHP functional again. Contribute to ephect-io/framework development by creating an account on GitHub.">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">
    <meta property="og:title" content="ephect-io/framework: Make PHP functional again">
    <meta property="og:url" content="https://github.com/ephect-io/framework">
    <meta property="og:description"
        content="Make PHP functional again. Contribute to ephect-io/framework development by creating an account on GitHub.">

    <link crossorigin="anonymous" media="all" rel="stylesheet" href="/css/app.css">
    <link crossorigin="anonymous" media="all" rel="stylesheet" href="/css/index.css">

    <script type="module" src="js/runtime/CodeWriter/CodeWriter.mjs"></script>
    <script type="module" src="js/runtime/TextWriter/TextWriter.mjs"></script>
</head>

<body>
    <div class="App">

        <header>
            <img src="/img/salamandra.svg" class="App-logo" alt="logo">
        </header>

        <div class="App-content">
            <div class="position-relative js-header-wrapper ">

                <p dir="auto">The code would look like this:</p>
                <CodeWriter source="/Com/code-writer.html" use-highlight-js="true" theme="base16/monokai" language="php"/>

            </div>
        </div>

        <footer>
            <div>
                C'est le pied
            </div>
        </footer>

    </div>

</body>

</html>