<?php
namespace QuickStart;

use function Ephect\Hooks\useEffect;

/**
 * @param $props
 * @return string
 */
#[ResponseHeader(contentType: "application/json")]
function Response($props): string
{
    useEffect(function($props, /* array */ $response) {
        $proposition = $props->myNameIs;
        $response = json_encode(["answer" => "Hello $proposition!"]);
    });

    return (<<<HTML
    <ResponseHeader 
        directive[]="Content-Type: application/json"
        directive[]="Content-Encoding: utf-8"
    />
    {{ response }}
    HTML);
}
