<?php

namespace QuickStart;

use Com as QuickStartCom;

use function Ephect\Hooks\useState;

function Home()
{
    useState(['m' => ['n' => 'with a']]);

    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect in action !</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
            <CodeWriter source="/Com/Com.html" use-highlight-js="false" />
            <QuickStartCom message="Hello World!" from="the app" />
        </div>
        <Slot name="javascripts">
            <script src="js/ephect.js"></script>
            <script type="module" src="js/runtime/CodeWriter.mjs"></script>
        </Slot>
    </Mother>
    HTML);
}
