<?php

namespace Ephect\Plugins\Route;

use Ephect\Components\Component;
use Ephect\Plugins\Router\RouterService;

use function Ephect\Hooks\useEffect;

function Route($props)
{
    useEffect(function () use($props) {
        $routeBuilder = new RouteBuilder($props);
        $route = $routeBuilder->build();

        $router = new RouterService();
        $router->addRoute($route->getMethod(), $route->getRule(), $route->getRedirect());
        $router->saveRoutes();
        $router->shiftRegistry();

        if(!IS_WEB_APP) {
            return;
        }
        
        $match = $router->matchRoute($route);

        if($match !== null) {
            list($path, $query) = $match;
            $comp = new Component($path);
            $comp->render();
        }

    });

    return (<<< HTML
        
    HTML);
}
