<?php

namespace Ephect\Plugins\Route;

use Ephect\Components\Component;
use Ephect\Plugins\Router\RouterService;
use Ephect\Registry\ComponentRegistry;

use function Ephect\Hooks\useEffect;

function Route($props)
{
    useEffect(function () use($props) {
        $routeBuilder = new RouteBuilder($props);
        $route = $routeBuilder->build();

        $router = new RouterService();
        $router->addRoute($route);
        $router->saveRoutes();

        /**
         * BEGIN code to remove if CLI build is mandatory
         */
        if(!IS_WEB_APP) {
            return;
        }

        $error = $route->getError();
        
        [$path, $query, $code] = $router->matchRoute($route);

        $code = $error ?: $code;

        http_response_code($code);

        if($code === 200) {
            $comp = new Component($path);
            $comp->render($query);
        } else {
            $errorComp = ComponentRegistry::read($path);
            if($errorComp !== null) {
                $comp = new Component($path);
                $comp->render(); 
            }
        }
        /**
         * END code to remove if CLI build is mandatory
         */

    });

    return (<<< HTML
        
    HTML);
}
