<?php

namespace QuickStart\Pages;

use function QuickStart\Components\Additionals\Mother;
use function QuickStart\Components\Home\Com as QuickStartCom;

use function Ephect\Hooks\useStore;

function Home(): string
{
    useStore(['m' => 'with a']);

    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect in action !</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
            <text-writer source="/Com/Com.html" styles="/css/app.css" classes="App-content" ></text-writer>
            <QuickStartCom message="Hello World!" from="the app" />
        </div>
        <Slot name="javascripts">
            <script type="module" src="/modules/human-writes.min.js"></script>
        </Slot>
    </Mother>
    HTML);
}
