<?php

namespace Ephect\Modules\Html;

use Ephect\Modules\Html\HtmlSaverService;
use function Ephect\Hooks\useEffect;

function HtmlSaver($children): string
{
    useEffect(function($children, $service) {
        $service = new HtmlSaverService($children);
    });

    return (<<< HTML
        @if %service->canRender() do
        {{ children }}
        @done
        <% 
            if(!%service->isPending()) {
                %html = { children };
                %service->storeHTML(%html);
                %service->markAsPending();
            }
        %>
    HTML);
}
