<?php

namespace Ephect\Plugins\Route;

use Ephect\Plugins\Router\RouterService;
use stdClass;
use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useStateObject;

function Route($children): string
{
    useEffect(function ($children, /* bool */ $onError, /* string */ $html) {

        $props = $children;
        if(method_exists($children, "props")) {
            $args = $children->props();

            $props = new stdClass;
            foreach ($args as $field => $value) {
                $props->{$field} = urldecode($value);
            }
        }

        $routeBuilder = new RouteBuilder($props);
        $route = $routeBuilder->build();

        $router = new RouterService();
        $router->addRoute($route);
        $router->saveRoutes();

        if (!IS_WEB_APP) {
            return;
        }

        $error = $route->getError();

        [$path, $query, $code] = $router->matchRoute($route);

        [$state, $setState] = useStateObject();
        $routes = $state->routes ?? [];

        $routes[] = ['path' => $path, 'query' => $query, 'error' => $error, 'code' => $code,];
        useStateObject(['routes' => $routes]);

    });

    return (<<< HTML

    HTML);
}
