<?php

namespace Ephect\Plugins\Route;

use Ephect\Plugins\Router\RouterService;
use stdClass;
use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useState;

function Route($children): string
{
    useEffect(function ($children, /* bool */ $onError, /* string */ $html) {

        $props = $children;
        if(method_exists($children, "props")) {
            $props = $children->props();
        }

        $routeService = new RouteService();
        $routeService->aggregateMiddlewares();

        $routeBuilder = new RouteBuilder($props);
        $route = $routeBuilder->build();

        $router = new RouterService();
        $router->addRoute($route);
        $router->saveRoutes();

        if (!IS_WEB_APP) {
            return;
        }

        $error = $route->getError();

        [$path, $query, $code] = $router->matchRoute($route);

        [$state, $setState] = useState();
        $routes = $state->routes ?? [];

        array_push($routes, ['path' => $path, 'query' => $query, 'error' => $error, 'code' => $code,]);
        useState(['routes' => $routes]);

    });

    return (<<< HTML

    HTML);
}
