<?php
namespace Ephect\Plugins;

use function Ephect\Hooks\useEffect;

function ResponseHeader($props)
{
    useEffect(function () use ($props, /* bool */ &$hasDirective, /* string */ &$directive) {
        $directive = $props->directive;
        $hasDirective = ($directive !== '');
    });

    return (<<< HTML
    <? 
        if (&hasDirective) {
            header("&directive");
        }
    ?>
    HTML);
}
