<?php

namespace Ephect\Modules\Authentication\Forms\Pages;

use function Ephect\Modules\Authentication\Forms\Components\Csrf;
use function Ephect\Modules\Http\Forms\ResponseHeader;

use Ephect\Framework\Crypto\Crypto;
use Ephect\Modules\Http\Transport\Request;
use Ephect\Modules\Notifier\Base\Notification;

use function Ephect\Modules\Authentication\Hooks\useAuthenticator;

function Login($props): string
{
    $isAuthenticated = false;
    $csrfToken = Crypto::createToken();
    if($props->submit ?? false) {
        $authenticator = useAuthenticator();
        $notification = new Notification();

        $email = $props->email ?? '';
        $password = $props->password ?? '';

        $isAuthenticated = $authenticator->authenticate(
            $email,
            $password,
        );

        if (!$isAuthenticated) {
            $notification->setError('Bad credentials.');
        }

        $notification->setSuccess('You are now logged in.');
    }

    return (<<< HTML

    @if %isAuthenticated do
        <-- ResponseHeader directives[]="location: /dashboard" / -->
    @done

    <h1>Login</h1>

    <form action="/login" method="post">
        <Csrf name="csrf_token" token="%csrfToken" />
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input name="email" type="text" class="form-control" id="email" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input name="password" type="password" class="form-control" id="password" required>
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
    </form>
    HTML);
}