<?php

namespace Ephect\Modules\Authentication\Forms\Pages;

use Ephect\Modules\Authentication\Forms\Components\Csrf;
use Ephect\Modules\Http\Forms\ResponseHeader;

function Logout(object $props): string
{
    $authenticator = $props->authenticator;
    $notification = $props->notification ?? null;
 
    $authenticator->logout();
    $notification->setSuccess('See you soon!');

    return (<<< HTML
    <ResponseHeader directives[]="location: /" />
    HTML);
}