<?php

namespace Ephect\Modules\Authentication\Forms\Pages;

use Ephect\Modules\Notifier\Base\Notification;

use function Ephect\Modules\Authentication\Hooks\useAuthenticator;
use function Ephect\Modules\Http\Forms\ResponseHeader;

function Logout($props): string
{
    $authenticator = useAuthenticator();
    $notification = new Notification();
 
    $authenticator->logout();
    $notification->setSuccess('See you soon!');

    return (<<< HTML
    <ResponseHeader directives[]="location: /" />
    @op exit
    HTML);
}