<?php

namespace Fun;

use \Fun\Com;

function App()
{
    return (<<<HTML
    <html>
    <head>
        <title>FunCom in action !</title>
        <link rel="stylesheet" href="css/index.css" >
        <link rel="stylesheet" href="css/app.css" >
    </head>
    <body>
        <div class="App" >
            <Header />
            <div class="App-content" >
                <Com message='Hello World!' />
            </div>
            <Footer />
        </div>
    </body>
    </html>

    HTML);
}
