<?php

namespace Fun;

use function Ephect\Hooks\useState;

function Start($props)
{
    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect setup !</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
            <link rel="stylesheet" href="/css/setup.css" />
        </Slot>
        <div class="App-content" >
            <Setup />
        </div>
        <Slot name="javascripts">
            <script src="/js/ephect.js"></script>
            <script src="/js/setup.js"></script>
        </Slot>
    </Mother>
    HTML);
}
