<?php

namespace Ephect\Plugins\Setup;

use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useQueryArgument;
use function Ephect\Hooks\useState;

define('SERVER_ERROR', 'Something went wrong, please check the server setup');

function Setup()
{

    useEffect(function () use (/* bool */ &$hasResponse, /* string */ &$response) {

        [$props, $setProps] = useState();

        $action = $props->action;
        // $action = useQueryArgument('action');
        $setup = new SetupService;

        if ($action === 'rewrite') {

            $ok = $setup->findFramework();
            $rewritebase = $setup->fixRewritBase();
            $response = json_encode(
                [
                    'result' => ($rewritebase !== null) ? $rewritebase : SERVER_ERROR,
                    'error' => ($rewritebase === null)
                ]
            );
        }

        if ($action === 'js') {
            $ok = $setup->installPhinkJS();
            $response = json_encode(
                [
                    'result' => ($ok) ? 'Javascript framework installation successful' : SERVER_ERROR,
                    'error' => !$ok
                ]
            );       
        }

        if ($action === 'index') {

            $ok = $setup->makeBootstrap();
            $ok = $ok && $setup->makeIndex();
            $response = json_encode(
                [
                    'result' => ($ok) ? 'Index created' : SERVER_ERROR,
                    'error' => !$ok
                ]
            );        
        }

        $hasResponse = ($response !== '');
    });

    return (<<< HTML
    {? 
        if ({hasResponse}) {
            header('Content-Type: application/json');
            return {response};
        }
    ?}
        <>
            <header>
                <h1>
                    Ephect Setup
                </h1>
            </header>
            <main>
                <section>
                    <h3>
                        Processing through steps, please wait ...
                    </h3>
                </section>
                <section>
                    <div class="border">&nbsp;</div>
                    <div class="content">
                        <div class="subborder">&nbsp;</div>

                        <ul>
                            <li>
                                <div class="caption">Fix .htaccess RewriteBase</div>
                                <div data-step="1" class="step uncheck">...</div>
                            </li>
                            <li>
                                <div class="caption">Download JS framework</div>
                                <div data-step="2" class="step uncheck">...</div>
                            </li>
                            <li>
                                <div class="caption">Make the index file</div>
                                <div data-step="3" class="step uncheck">...</div>
                            </li>
                        </ul>
                        <div class="subborder">&nbsp;</div>

                    </div>
                    <div class="border">&nbsp;</div>
                    <div class="clear"></div>
                </section>
                <section>
                    <h3>
                        You will be redirected to the Welcome page
                    </h3>
                </section>
            </main>
            <footer>

            </footer>
        </>
    HTML);
}
