<?php

namespace Ephect\Plugins\Setup;

function Setup()
{
    return (<<< HTML
        <>
            <header>
                <h1>
                    Ephect Setup
                </h1>
            </header>
            <main>
                <section>
                    <h3>
                        Processing through steps, please wait ...
                    </h3>
                </section>
                <section>
                    <div class="border">&nbsp;</div>
                    <div class="content">
                        <div class="subborder">&nbsp;</div>

                        <ul>
                            <li>
                                <div class="caption">Fix .htaccess RewriteBase</div>
                                <div data-step="1" class="step uncheck">...</div>
                            </li>
                            <li>
                                <div class="caption">Download JS framework</div>
                                <div data-step="2" class="step uncheck">...</div>
                            </li>
                            <li>
                                <div class="caption">Make the index file</div>
                                <div data-step="3" class="step uncheck">...</div>
                            </li>
                        </ul>
                        <div class="subborder">&nbsp;</div>

                    </div>
                    <div class="border">&nbsp;</div>
                    <div class="clear"></div>
                </section>
                <section>
                    <h3>
                        You will be redirected to the Welcome page
                    </h3>
                </section>
            </main>
            <footer>

            </footer>
        </>
    HTML);
}
