<?php

namespace Ephect\Modules\Forms\Forms;

use Ephect\Modules\Forms\Services\HtmlSaverService;
use function Ephect\Hooks\useEffect;

function HtmlSaver($children): string
{
    $service = new HtmlSaverService($children);

    return (<<< HTML
        @if %service->canRender() do
        {{ children }}
        @done
        <% 
            if(!%service->isPending()) {
                %html = { children };
                %service->storeHTML(%html);
                %service->markAsPending();
            } elseif (%service->canRefresh()) {
                %html = { children };
                %service->storeHTML(%html);
            }
        %>
    HTML);
}
