<?php

namespace Fun;

function Child()
{
    return (<<<HTML
    <Parent>
        <Block name="title">Ephect!</Block>
        <Block name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Block>
        <Block name="main">
            <section>
                <p>
                    Hello&nbsp;
                    <Echo var="firstname" />!
                </p>
                <p>This is reed</p>
                <p>again</p>
            </section>
        </Block>
        <Block name="second">
            <section>
                <p>
                    Me
                </p>
                My computer
                will be stunning
            </section>
        </Block>
        <Block name="javascripts">
            <script src="/js/ephect.js"></script>
        </Block>

    </Parent>
    HTML);
}