<?php

namespace Fun;

use function Ephect\Hooks\useEffect;

function Child()
{

    useEffect(function() use (&$firstname) {
        $firstname = "David";
    });

    return (<<<HTML
    <Parent>
        <Block name="title">Ephect!</Block>
        <Block name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Block>
        <Block name="main">
            <section>
            <h2>Main</h2>
                <p>
                    Hello&nbsp;{ firstname }!
                </p>
                <p>This is reed</p>
                <p>again</p>
            </section>
        </Block>
        <Block name="second">
            <section>
            <h2>Second</h2>
                <p>
                    Me
                </p>
                My computer
                will be stunning
            </section>
        </Block>
        <Block name="javascripts">
            <script src="/js/ephect.js"></script>
        </Block>
    </Parent>
        <!-- EOF -->
    HTML);
}