<?php

namespace Fun;

function Child()
{
    $firstname = 'David';

    $vars = ["filename" => $firstname];

    return (<<<HTML
    <Mother props={$vars}>
        <Block name="title">Welcome!</Block>
        <Block name="stylesheets">
            <link rel="stylesheet" href="css/pond-theme.css" />
            <link rel="stylesheet" href="css/pond.css" />
        </Block>
        <Block name="main">
            <section>
                <p>
                    Hello&nbsp;
                    {{ firstname }}!
                </p>
                <Block name="submain">
                    <p>This is reed</p>
                    <p>again</p>
                </Block>
            </section>
        </Block>
        <Block name="second">
            <section>
                <Block name="person">
                    <p>
                        Me
                    </p>
                    <Block name="attributes">
                        My computer
                        <Block name="attributes">
                            will be stunning
                        </Block>
                    </Block>
                </Block>
            </section>
        </Block>
        <Block name="javascripts">
            <script src="js/pond.js"></script>
        </Block>
    </Mother>
    HTML);
}
