<?php
namespace Fun;

use function Ephect\Hooks\useEffect;
use function Ephect\Hooks\useState;

function Com($props)
{
    useEffect(function() use ($props, &$b, &$c, &$d, &$m) {
        $b = 'It is a';
        $c = 'functional component';
        $d = $props->from;
        $m = useState('m', 'n');
        
    });

    return (<<<HTML
    <h1>{{ props->message }}</h1>
    <sub>from {{ d }}</sub>
    <h2>{{ b }}</h2>
    <h3>{{ c }}</h3>
    <h3>{{ m }}</h3>
    <Dummy />
    HTML);
}
