<?php

namespace Fun;

use Com as Ephect;

use function Ephect\Hooks\setState;

function Home()
{
    setState('m', ['n' => 'o']);

    return (<<<HTML
    <Mother>
        <Block name="title">Ephect in action !</Block>
        <Block name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Block>
        <div class="App-content" >
            <Ephect message='Hello World!' from="the app" />
        </div>
        <Block name="javascripts">
            <script src="js/ephect.js"></script>
        </Block>
    </Mother>
    HTML);
}
