<?php

namespace Fun;

function Mother($children)
{

    return (<<<HTML
    <head>
        <meta charset="UTF-8">
        <title>
            Mother!
        </title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
        <Block name="stylesheets">
        </Block>
    </head>

    <body>
        <div class="App" >
        <HeaderAndFooter>
            {{ children }}
        </HeaderAndFooter>
        </div>
    </body>
    HTML);
}