<?php

namespace Fun;

use Ephect\Components\ComponentEntity;
use Ephect\Components\ComponentStructure;
use Ephect\Components\Composition;
use Ephect\Components\Generators\ComponentParser;
use Ephect\Components\View;

use function Ephect\Hooks\useEffect;

function Second()
{

    $code = '';
    useEffect(function() use (&$code) {

        $view = new View();
        $view->load('components/fun/home.phtml');
        $view->analyse();

        $parser = new ComponentParser($view);
        $list = $parser->doComponents();

        $depths = $parser->getIdListByDepth();

     
        $compose = new Composition($view->getFullyQualifiedFunction());
        
        foreach ($list as $item) {
            $entity = new ComponentEntity(new ComponentStructure($item));
            $compose->items()->add($entity);
        }

        $compose->bindNodes();

        $composition = $compose->toArray();

        $code = json_encode(['Fun\\App' => ['depths' => $depths, 'composition' => $composition]], JSON_PRETTY_PRINT);
    });

    return (<<<HTML
        <pre>
        {{ code }}
        </pre>
    HTML);
}