<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>
        <phx:block name="title">Welcome!</phx:block>
    </title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    <phx:block name="stylesheets"></phx:block>
</head>

<body>


    <div class="App">
        <header>
            <img src='/img/salamandra.svg' class='App-logo' alt='logo' />
        </header>
        <div class="App-content">
        <main>
            <phx:block name="main">
            </phx:block>
            <phx:block name="second">
            </phx:block>

        </main>
        </div>
        <footer>
            <div>
                C'est le pied
            </div>
        </footer>
    </div>

    <phx:block name="javascripts"></phx:block>
</body>

</html>