<phx:extends template="master.phtml" />
<phx:block name="title">Welcome!</phx:block>
<phx:block name="stylesheets">
    <link rel="stylesheet" href="/css/index.css" />
    <link rel="stylesheet" href="/css/app.css" />
</phx:block>
<phx:block name="main">
    <section>
        <p>
            Hello&nbsp;
            <phx:echo var="firstname" />!
        </p>
            <p>This is reed</p>
            <p>again</p>
    </section>
</phx:block>
<phx:block name="second">
    <section>
            <p>
                Me
            </p>
                My computer
                    will be stunning
    </section>
</phx:block>


<phx:block name="javascripts">
    <script src="/js/funcom.js"></script>
</phx:block>
