<?php

namespace QuickStart;

use function Ephect\Modules\Routing\Forms\Router;
use function Ephect\Modules\Routing\Forms\Route;

function Switcher(): string
{
    return (<<< HTML
    <Router>
        <Route method="GET" rule='/' exact="true" redirect="Home" />
        <Route method="GET" rule='/hello/(name)/(lname)' exact="true" redirect="Hello" />
        <Route method="GET" rule='/world\\?name=(.*)&lname=(.*)' exact="true" redirect="World" />
        <Route method="GET" rule='/world/?' exact="true" redirect="World" />
        <Route method="GET" rule='/matriochka/(devotchka)' exact="true" redirect="Matriochka0" />
        <Route method="GET" rule='/matriochka/?' exact="true" redirect="Matriochka0" />
        <Route method="GET" rule='/info/?' exact="true" redirect="Info" />
        <Route method="GET" rule='/callback' exact="true" redirect="Callback" />
        <Route method="POST" rule='/response' exact="true" redirect="Response" />
    </Router>
    HTML);
}
