<?php

namespace Fun;

function Matroichka0()
{

    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect in action !</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
        0&nbsp;
            <Matroichka1>
                1&nbsp;
                <Matroichka2>
                2&nbsp;

                </Matroichka2>
            </Matroichka1>

        </div>
        <Slot name="javascripts">
            <script src="js/ephect.js"></script>
        </Slot>
    </Mother>
    HTML);
}
