<?php

namespace Fun;

use function Ephect\Hooks\useQueryArgument;
use function Ephect\Hooks\useSlot;

function Second()
{

    useSlot(function() use (/* string */ &$firstname, /* string */ &$adjective) {
        $firstname = useQueryArgument('name', "David");
        $adjective = "stunning";
    });

    return (<<< HTML
    <First>
        <Slot name="title">Ephect!</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <Slot name="main">
            <section>
            <h2>Main</h2>
                <p>
                    Hello&nbsp;{{ firstname }}!
                </p>
            </section>
        </Slot>
        <Slot name="second">
            <section>
            <h2>Second</h2>
                <p>
                Your computer is <strong> {{ adjective }} </strong>
                </p>
            </section>
        </Slot>
        <Slot name="javascripts">
            <script src="/js/ephect.js"></script>
        </Slot>
    </First>
    HTML);
}