<?php

namespace Fun;

function Start()
{
    return (<<< HTML
    <Mother>
        <Slot name="title">Ephect in action !</Slot>
        <Slot name="stylesheets">
            <link rel="stylesheet" href="/css/index.css" />
            <link rel="stylesheet" href="/css/app.css" />
        </Slot>
        <div class="App-content" >
        <Setup />
        </div>
        <Slot name="javascripts">
            <script src="js/ephect.js"></script>
        </Slot>
    </Mother>
    HTML);
}
