<?php

namespace Fun;

function Switcher()
{
    return (<<< HTML
    <Router>
        <Route method="GET" rule='^/$' redirect="Home" />
        <Route method="GET" rule='^/hello\\?(.*)$' redirect="Hello" />
        <Route method="GET" rule='^/info(/)?$' redirect="Info" />
        <Route method="GET" rule='^/second(/)?\\?(.*)?$' redirect="Second" />
        <Route method="GET" rule='^/second(/)?$' redirect="Second" />
        <Route method="GET" rule='^/start(/)?\\?(.*)?$' redirect="Start" />
        <Route method="GET" rule='^/start(/)?$' redirect="Start" />
    </Router>
    HTML);
}
