<?php

namespace Fun;

use function Ephect\Hooks\useProps;

function Hello($props) {

    [$name] = useProps($props, function($props, /* string */ $name) {
        $name = $props->name;

        return [$name];
    });

    return (<<< HTML
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8">
            <title>
                Hello
            </title>
        </head>
        <body>
        
            Hello {{ name }}

        </body>
    </html>
    HTML);
}
