<?php

namespace Ephect\Plugins\Router;

use Ephect\Components\Component;
use Ephect\Components\ComponentEntity;
use Ephect\Registry\CodeRegistry;
use Ephect\Registry\Registry;

use function Ephect\Hooks\useEffect;

function Router($children)
{
    useEffect(function () use (/* bool */ &$hasRouted) {

        CodeRegistry::uncache();
        $items = CodeRegistry::items();

        $service = new RouterService;

        if ($service->tryRouting()) {

            $route = $service->doRouting();
            if ($route !== null) {
                list($path, $query) = $route;
                $comp = new Component($path);
                $comp->render();
            }
            $hasRouted = true;
            return;
        }

        foreach ($items as $type => $declaration) {
            $router = null;
            $composition = $declaration['composition'];
            foreach ($composition as $child) {
                if ($child['name'] == 'Router') {
                    $entity = ComponentEntity::buildFromArray($composition);
                    $router = $entity->toArray();
                }
            }
            if ($router !== null) {
                Registry::write('router', $router);
                break;
            }
        }
    });

    return (<<< HTML
        {? if({hasRouted}) { return ''; } ?}
        {{ children }}
    HTML);
}
