<?php

namespace Ephect\Plugins\Router;

use Ephect\Components\Component;
use Ephect\Registry\CodeRegistry;
use Ephect\Registry\Registry;

use function Ephect\Hooks\useEffect;

function Router($children)
{

    $hasRouted = false;
    useEffect(function () use (&$hasRouted) {

        CodeRegistry::uncache();
        $items = CodeRegistry::items();

        $service = new RouterService;

        if($service->tryRouting()) {

            $route = $service->doRouting();
            if($route !== null) {
                list($path, $query) = $route;
                Component::render($path);
            }
            $hasRouted = true;
            return;
        }

        foreach ($items as $component => $composition) {
            $router = null;
            $c = count($composition);
            for ($i = 0; $i < $c; $i++) {
                $child = $composition[$i];
                if ($child['name'] == 'Router') {
                    $router = $child;
                }
            }
            if ($router !== null) {
                Registry::write('router', $router);
                break;
            }
        }
    });

    return (<<<HTML
        <?php if($hasRouted) { return ''; } ?>
        {{ children }}
    HTML);
}
