<?php
namespace Ephect\Modules\Http\Forms;

use function Ephect\Hooks\useEffect;

function ResponseHeader($props): string
{
    useEffect(function ($props, /* bool */ $hasDirectives, /* array */ $directives) {
        $directives = $props->directive;
        $hasDirectives = count($directives) > 0;
    });

    return (<<< HTML
    @if %hasDirectives do        
        @for %directives as %directive do
            header(%directive);
        @done
    @done
    HTML);
}
